ARG AEM_RUNMODE=author
ARG HTTP_PORT=4502
ARG SERVICE_PACKAGE_VERSION=6.4.3

FROM ${AEM_RUNMODE}:6.4-slim

ENV AEM_RUNMODE ${AEM_RUNMODE}
ENV HTTP_PORT ${HTTP_PORT}
ENV SERVICE_PACKAGE_VERSION ${SERVICE_PACKAGE_VERSION}

COPY scripts/install-service-package.sh /tmp/
COPY scripts/tools.sh /tmp/
COPY files/aem-service-pkg-*.zip /tmp/

RUN /tmp/install-service-package.sh && \
    rm -rf /tmp/*
